
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-common-configmap
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/config.yaml
data: 
  key1: val1
  key2: val2
  key3: val3