apiVersion: ops.plivo.com/v1alpha1
kind: WebService
metadata:
  name: nginx
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/nginx
spec:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"
  entrypoint:
    command: []
    args: []
  autoscaling:
    controller: HorizontalPodAutoscaler
    maxReplicas: 100
    minReplicas: 1
    averageCPUUtilizationTarget: 70
    averageMemoryUtilizationTarget: 70
  persistence:
    enabled: false
    storageClass: gp3
    storageSize: 10
    mountPath: /data
  deployment:
    automateImageUpdates: false
    applicationRepositoryBranch: main
  loadbalancing:
    useCommonLoadbalancer: true
    public: false
    externalDNSNames: []
    customListenerRules: []
    listenerPorts: 
    - 443
    targetGroup:
      healthcheck:
        path: /
        initialDelaySeconds: 0
  securityContext:
    runAsUser: 10001
    runAsNonRoot: true
    runAsGroup: 10001
  consul: "https://consul.non-prod.plivops.com"
  containerPort: 80
  image: nginx
  advanced:
    additionalEnvVars: {}
  configuration: 
  - name: devops-common-nginx-configmap
    usageMethod: AsEnvVariables
    sensitive: false
  - name: devops-common-nginx
    usageMethod: AsEnvVariables
    sensitive: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-common-nginx-configmap
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/nginx
data: 
  key1: val1
  key2: val2
  key3: val3
