apiVersion: ops.plivo.com/v1alpha1
kind: WebService
metadata:
  name: sample
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/sample
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  entrypoint:
    command: [cmd]
    args: [arg]
  autoscaling:
    controller: HorizontalPodAutoscaler
    maxReplicas: 10
    minReplicas: 5
    averageCPUUtilizationTarget: 60
    averageMemoryUtilizationTarget: 60
  persistence:
    enabled: true
    storageClass: gp3
    storageSize: 19
    mountPath: /data
  deployment:
    automateImageUpdates: true
    applicationRepositoryBranch: main
  loadbalancing:
    useCommonLoadbalancer: true
    public: true
    externalDNSNames: [sample.plivo.com]
    customListenerRules: []
    listenerPorts: [443]
    targetGroup:
      healthcheck:
        path: /
        initialDelaySeconds: 11
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0
  consul: "https://consul.non-prod.plivops.com"
  containerPort: 8080
  image: "nginx:latest"
  advanced:
    additionalEnvVars: 
      key: value
