
apiVersion: ops.plivo.com/v1alpha1
kind: ScheduledTask
metadata:
  name: scheduler
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/scheduler
spec:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  entrypoint:
    command: []
    args: []
  persistence:
    enabled: false
    storageClass: gp3
    storageSize: null
    mountPath: /data
  lifecycle:
    restartPolicy: OnFailure
    backoffLimit: 6
    ttlSecondsAfterFinished: 21600
  deployment:
    suspend: false
    automateImageUpdates: false
    applicationRepositoryBranch: null
  securityContext:
    runAsUser: 10001
    runAsNonRoot: true
    runAsGroup: 10001
  image: scheduler
  schedule: "* * * * *"
  advanced:
    exposePodInfo: false
    serviceAccount: null
    additionalEnvVars: {}
