apiVersion: ops.plivo.com/v1alpha1
kind: ScheduledTask
metadata:
  name: scheduler
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/scheduler
spec:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  entrypoint:
    command:
      - cmd
    args:
      - arg
  persistence:
    enabled: true
    storageClass: gp3
    storageSize: 20
    mountPath: /data
  lifecycle:
    restartPolicy: OnFailure
    backoffLimit: 6
    activeDeadlineSeconds: 100
    ttlSecondsAfterFinished: 21600
  deployment:
    suspend: false
    startingDeadlineSeconds: 10
    automateImageUpdates: true
    applicationRepositoryBranch: main
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0
  image: scheduler
  schedule: "* * * * *"
  advanced:
    exposePodInfo: true
    serviceAccount: sample
    additionalEnvVars:
      sample: value
  configuration:
    - name: devops-common-scheduler
      usageMethod: AsEnvVariables
      sensitive: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-common-scheduler
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/scheduler
data: 
  key1: val1
  key2: val2
  key3: val3
