apiVersion: ops.plivo.com/v1alpha1
kind: Worker
metadata: 
  name: worker
  namespace: devops
  annotations:
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/devops/devops-common/worker
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  entrypoint:
    command: [cmd]
    args: [arg]
  deployment:
    automateImageUpdates: true
    applicationRepositoryBranch: main
  autoscaling:
    controller: HorizontalPodAutoscaler
    maxReplicas: 10
    minReplicas: 5
    averageCPUUtilizationTarget: 60
    averageMemoryUtilizationTarget: 60
  image: "worker:latest"
  consul: "https://consul.non-prod.plivops.com"
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0
  advanced:
    additionalEnvVars: 
      key: value
