apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-dev-sms-noncluster
  namespace: messaging
  annotations:
    redis.plivo.com/bandwidth: 0
    redis.plivo.com/userMemory: 2048mb
    redis.plivo.com/throughput: 0
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/messaging/messaging-common/resources/redis-dev-sms-noncluster.yaml
spec:
  releaseName: redis-dev-sms-noncluster
  interval: 1m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: redis-sentinel
      version: 20.1.5
      sourceRef:
        kind: GitRepository
        name: devops-helm-charts
        namespace: flux-system
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
      repository: plivo/bitnami-redis/redis-7.4.0
      tag: 25.02.28.1484
    auth:
      enabled: false
      sentinel: false
    metrics:
      enabled: true
      image:
        registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
        repository: plivo/bitnami-redis/redis-exporter-1.63.0
        tag: 25.02.26.1481
      resources:
        limits:
          ephemeral-storage: 2Gi
          memory: 20Mi
        requests:
          ephemeral-storage: 50Mi
          memory: 20Mi
    architecture: replication
    useHostnames: true
    commonConfiguration: |-
      bind 0.0.0.0
      maxmemory 2048mb
      maxmemory-policy noeviction
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      save 900 1
      save 300 10
      save 60 10000
    replica:
      extraFlags:
      - '--loadmodule /opt/bitnami/redis/modules/redisjson.so'
      persistence:
        enabled: true
        storageClass: gp3
        size: 6Gi
      resources:
        requests:
          memory: 2088Mi
        limits:
          memory: 2088Mi
      replicaCount: 2
      tolerations:
      - key: ops.plivo.com/dedicated-for
        value: messaging
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - redis-dev-sms-noncluster
    sentinel:
      image:
        registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
        repository: plivo/bitnami-redis/redis-sentinel-7.4.0
        tag: 25.02.26.1480
      enabled: true
      quorum: 2
      configuration: |
        sentinel down-after-milliseconds master 1000
      resources:
        requests:
          memory: 20Mi
        limits:
          memory: 20Mi
      masterSet: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-extra-sentinel-dev-sms-noncluster
  namespace: messaging
  labels:
    app: redis-extra-sentinel-dev-sms-noncluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-extra-sentinel-dev-sms-noncluster
  template:
    metadata:
      labels:
        app: redis-extra-sentinel-dev-sms-noncluster
    spec:
      tolerations:
      - key: ops.plivo.com/dedicated-for
        value: messaging-redis-sentinel-spot
      containers:
      - name: sentinel
        image: 857556598075.dkr.ecr.us-west-1.amazonaws.com/plivo/bitnami-redis/redis-sentinel-7.4.0:25.02.26.1480
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: sentinel
          containerPort: 26379
        env:
        - name: REDIS_MASTER_SET
          value: master
        - name: REDIS_MASTER_HOST
          value: redis-dev-sms-noncluster-node-0.redis-dev-sms-noncluster-headless.messaging.svc.cluster.local
        - name: REDIS_MASTER_PORT_NUMBER
          value: '6379'
        - name: REDIS_SENTINEL_QUORUM
          value: '2'
        - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
          value: '1000'
        - name: REDIS_SENTINEL_FAILOVER_TIMEOUT
          value: '180000'
        - name: REDIS_SENTINEL_RESOLVE_HOSTNAMES
          value: 'yes'
        readinessProbe:
          exec:
            command:
            - bash
            - '-lc'
            - /opt/bitnami/redis-sentinel/bin/redis-cli -p 26379 ping | grep PONG
          initialDelaySeconds: 5
          periodSeconds: 5
