apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-mps-sharq
  namespace: messaging
  annotations:
    redis.plivo.com/bandwidth: 0
    redis.plivo.com/userMemory: 5000mb
    redis.plivo.com/throughput: 0
    filepath: clusters/pre-prod/pre-prod-us-east-1/tenants/messaging/messaging-common/resources/redis-mps-sharq.yaml
spec:
  releaseName: redis-mps-sharq
  interval: 1m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: redis-sentinel
      version: 20.1.5
      sourceRef:
        kind: GitRepository
        name: devops-helm-charts
        namespace: flux-system
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
      repository: plivo/bitnami-redis/redis-7.4.0
      tag: 25.02.28.1484
    auth:
      enabled: false
      sentinel: false
    metrics:
      enabled: true
      image:
        registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
        repository: plivo/bitnami-redis/redis-exporter-1.63.0
        tag: 25.02.26.1481
      resources:
        limits:
          ephemeral-storage: 2Gi
          memory: 20Mi
        requests:
          ephemeral-storage: 50Mi
          memory: 20Mi
    architecture: replication
    useHostnames: true
    commonConfiguration: |-
      bind 0.0.0.0
      maxmemory 5000mb
      maxmemory-policy noeviction
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      save 900 1
      save 300 10
      save 60 10000
    replica:
      extraFlags:
        - '--loadmodule /opt/bitnami/redis/modules/redisjson.so'
      persistence:
        enabled: true
        storageClass: gp3
        size: 15Gi
      resources:
        requests:
          memory: 5040Mi
        limits:
          memory: 5040Mi
      replicaCount: 2
      tolerations:
        - key: ops.plivo.com/dedicated-for
          value: messaging
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - redis-mps-sharq
      lifecycleHooks:
        postStart:
          exec:
            command:
              - /bin/bash
              - '-c'
              - |-
                nohup /bin/bash -c '(
                LOG_FILE=/tmp/poststart.err

                echo "Waiting for Redis to be ready..."
                until redis-cli ping | grep PONG; do 
                  sleep 1
                done

                echo "Loading Lua scripts efficiently..."

                for script in /luascripts/*.lua; do
                  [ -f "$script" ] || continue
                  echo "Processing $(basename "$script")..."

                  SHA=$(cat "$script" | xargs -0 redis-cli --raw SCRIPT LOAD 2>>$LOG_FILE)
                  if [ -z "$SHA" ]; then
                    echo "Error loading script: $(basename "$script")"
                    exit 1
                  fi

                  echo "$(basename "$script"): $SHA"
                done

                # Mark readiness for probe
                echo "All scripts loaded successfully."
                touch /tmp/scripts-loaded
                )' >/tmp/poststart.out 2>&1 & disown
      customReadinessProbe:
        exec:
          command:
            - sh
            - '-c'
            - |-
              if [ -f /tmp/scripts-loaded ]; then
                exec /health/ping_readiness_local.sh 1
              else
                exit 1
              fi
        initialDelaySeconds: 20
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      extraVolumes:
        - name: lua-scripts
          configMap:
            name: lua-redis-mps-sharq
      extraVolumeMounts:
        - name: lua-scripts
          mountPath: /luascripts
    sentinel:
      image:
        registry: 857556598075.dkr.ecr.us-west-1.amazonaws.com
        repository: plivo/bitnami-redis/redis-sentinel-7.4.0
        tag: 25.02.26.1480
      enabled: true
      quorum: 2
      configuration: |
        sentinel down-after-milliseconds master 1000
      resources:
        requests:
          memory: 20Mi
        limits:
          memory: 20Mi
      masterSet: master
    networkPolicy:
      enabled: true
      allowExternal: false
      allowExternalEgress: false
      extraIngress:
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: common-haproxy-redis
                  app.kubernetes.io/name: haproxy
          ports:
            - port: 6379
              protocol: TCP
        - from:
            - podSelector:
                matchLabels:
                  app: redis-extra-sentinel-mps-sharq
          ports:
            - port: 26379
              protocol: TCP
            - port: 6379
              protocol: TCP
      extraEgress:
        - to:
            - podSelector:
                matchLabels:
                  app: redis-extra-sentinel-mps-sharq
          ports:
            - port: 6379
              protocol: TCP
            - port: 26379
              protocol: TCP
      ingressNSMatchLabels: {}
      ingressNSPodMatchLabels: {}
      metrics:
        allowExternal: false
        ingressNSMatchLabels:
          kubernetes.io/metadata.name: monitoring
        ingressNSPodMatchLabels: {}
